# Generated by Django 5.2.8 on 2025-11-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
